import React from "react";

export const AltTxt = ({platform, post, index, setIndex}) => {
  const [answer, setAnswer] = React.useState("")
  return (
    answer === "" ? (
      <AltTxtQ platform={platform} setAnswer={setAnswer}/>
    ) : answer === "yes" ? (
      <Yes platform={platform} index={index} setIndex={setIndex} setAnswer={setAnswer}>Yes</Yes>
    ) : (
      <No platform={platform} index={index} setIndex={setIndex} setAnswer={setAnswer}>No</No>
    )
    )
}

export const AltTxtQ = ({setAnswer, platform }) => {
  return (
    <>
      <h1>Does your photo have alternate text (alt text)?</h1>
      <p>
      Alternate text (better known as alt text) is important for blind and low vision people who uses assistive technology like a screen reader or text-to-speech program to access digital content because it’s meant to accurately describe images to the user.
      </p>
      <p>
        Image descriptions are incredibly useful and any photos or gifs that you use on {platform} should have an alt text.
      </p>
      <p>Now that you know more about alt text and its benefits, does your photo have alt text accompanied with it?</p>
      
      <button onClick={() => setAnswer("yes")}>
        Yes
      </button>
      <button onClick={() => setAnswer("no")}>
        No
      </button>

    </>
  )
}



const Yes = ({index, setIndex, setAnswer, platform, post}) => {
  return(
  <>
      <h1>Perfect!</h1>
      <p>
        Below is a good example of a {post} that has alt text for their photos from the account WeRateDogs. It’s a bit difficult to tell if a photo has alt text or not on {platform}, especially if you are not using a screenreader. But when you inspect the code of the photo, you can see the alt text is written.
      </p>
      <p>
        The alt text of the photo is: “a little black and tan dachshund puppy stands poolside. he’s wearing a tiny teal hawaiian shirt with a white and pink floral print. the sun looks warm on his face, and the water is a picturesque shade of blue. someone please get him a coconut-shaped water bowl.”
      </p>
      <>
  <button onClick={() => setIndex(index + 1)}>
    Continue
  </button>
  <button onClick={() => setAnswer("")}>
    Go Back <span>&#8592;</span>
  </button>
</>
    </>
    )
}

const No = ({index, setIndex, setAnswer, platform}) => {
  return (
    <>
    <h1>It’s super simple!</h1>
    <p>
      I promise it won’t take too much extra time to add them.
    </p>
    <p>
      When you upload a photo on {platform}, it will automatically generates alt text. Don’t rely on this. These descriptions are often either too simple or plain wrong. Hover over the photo you want to add alt text to and click the edit button. Click “Override autogenerated alt text” to edit it and write your own! If you need more details, Facebook describes how to change alt text for your photos.
    </p>
    <h2>
      Best Practices for Writing Alt Text:
    </h2>
    <p>
      The accompanying thread is the descriptive text that describes the key details and parts of the trailer. You only need to describe the most important details. Since this will be read aloud, being too lengthy or wordy is not helpful. 
    </p>
    <p>
      A good way to test if the description is good or not is to get someone to read it aloud, close your eyes, and see if the text still is able to convey the most crucial scenes of the video well. 
    </p>
    <p>
      In addition, avoid any emojis or emoticons in your descriptive text. It doesn’t translate well through screen readers or text-to-speech programs.
    </p>
    <p>
      If you want to learn more about written descriptive text or other similar accommodations (like audio descriptions), this article gives a good overview of the various video descriptions available. 
    </p>
    <>
  <button onClick={() => setIndex(index + 1)}>
    Continue
  </button>
  <button onClick={() => setAnswer("")}>
    Go Back <span>&#8592;</span>
  </button>
</>
  </>)
}

export default AltTxt;