import React from "react";
import Button from "../../../components/Button";
import { Section, StyledTitle, ButtonPanel, QuizHeaders } from "../styling";
import Continue from "../../../components/Continue";
import {
  FacebookAltText,
  InstagramAltText,
  TwitterAltText,
  TwitterHowTo,
} from "./links";

export const AltTxt = ({ platform, post, index, setIndex }) => {
  const [answer, setAnswer] = React.useState("");
  console.log(platform, post, "platform and post");
  return (
    <Section>
      <StyledTitle>Alt Text</StyledTitle>
      {answer === "" ? (
        <AltTxtQ platform={platform} setAnswer={setAnswer} />
      ) : answer === "yes" ? (
        <Yes
          platform={platform}
          index={index}
          setIndex={setIndex}
          setAnswer={setAnswer}
        >
          Yes
        </Yes>
      ) : (
        <No
          platform={platform}
          index={index}
          setIndex={setIndex}
          setAnswer={setAnswer}
        >
          No
        </No>
      )}
    </Section>
  );
};

export const AltTxtQ = ({ setAnswer, platform }) => {
  return (
    <>
      <QuizHeaders>Does your photo have alternate text (alt text)?</QuizHeaders>
      <p>
        Alternate text (better known as alt text) is important for blind and low
        vision people who uses assistive technology like a screen reader or
        text-to-speech program to access digital content because it’s meant to
        accurately describe images to the user.
      </p>
      <p>
        Image descriptions are incredibly useful and any photos or gifs that you
        use on {platform} should have an alt text.
      </p>
      <p>
        Now that you know more about alt text and its benefits, does your photo
        have alt text accompanied with it?
      </p>
      <ButtonPanel>
        <Button onClick={() => setAnswer("yes")}>Yes</Button>
        <Button onClick={() => setAnswer("no")}>No</Button>
      </ButtonPanel>
    </>
  );
};

const Yes = ({ index, setIndex, setAnswer, platform, post }) => {
  return (
    <>
      <QuizHeaders>Perfect!</QuizHeaders>
      <p>
        Below is a good example of a {post} that has alt text for their photos
        from the account WeRateDogs.{" "}
      </p>
      {platform === "twitter" ? (
        <p>
          You should be able to tell if you properly attached alt text to your
          photos because an “ALT” button should appear at the bottom left corner
          of your photo when your Tweet is published."{" "}
        </p>
      ) : (
        <p>
          It’s a bit difficult to tell if a photo has alt text or not on{" "}
          {platform}, especially if you are not using a screenreader. But when
          you inspect the code of the photo, you can see the alt text is
          written.
        </p>
      )}
      {platform === "twitter" ? (
        <TwitterAltText />
      ) : platform === "facebook" ? (
        <FacebookAltText />
      ) : platform === "instagram" ? (
        <InstagramAltText />
      ) : null}
      {platform === "instagram" ? (
        <Continue
          index={index}
          setIndex={setIndex}
          setAnswer={setAnswer}
          pages={1}
        />
      ) : (
        <Continue
          index={index}
          setIndex={setIndex}
          setAnswer={setAnswer}
          pages={2}
        />
      )}
    </>
  );
};

const No = ({ index, setIndex, setAnswer, platform }) => {
  return (
    <>
      <QuizHeaders>It’s super simple!</QuizHeaders>
      <p>I promise it won’t take too much extra time to add them.</p>
      {platform === "twitter" ? (
        <p>
          When you upload a photo to your Tweet, you will select “Add
          description underneath the image.” Then, all you have to do is enter a
          description of the image in the text box. Now, when you publish your
          tweet, an “ALT” badge will appear and everyone can easily access the
          photos in your Tweet! If you want more detailed instructions, Twitter
          takes you through the steps of how to add alt text to Tweets.
        </p>
      ) : platform === "facebook" ? (
        <p>
          When you upload a photo on {platform}, it will automatically generates
          alt text. Don’t rely on this. These descriptions are often either too
          simple or plain wrong. Hover over the photo you want to add alt text
          to and click the edit button. Click “Override autogenerated alt text”
          to edit it and write your own! If you need more details, Facebook
          describes how to change alt text for your photos.
        </p>
      ) : platform === "instagram" ? (
        <p>
          Once you choose a photo to your Instagram, proceed as normal until you
          reach the part where you write your captions. You should see an
          “Advanced Settings” section and find “Write Alt Text.” If you’re
          uploading from your desktop, you will see an “Accessibility” section
          instead. Write your alt text and tap “Done” to save it. If you want
          more details, you can refer to Instagram’s guide on how to add alt
          text.
        </p>
      ) : null}
      <h2>Best Practices for Writing Alt Text:</h2>
      <p>
        So, now you know how to add alt text, but how do we write great and
        helpful alt text? Here are a few things to keep in mind:
      </p>
      <ol className="large-numbers">
        <li>
          Capture what’s important - Don’t get hung up on every little details.
          Think to yourself what part of the image is vital for your audience to
          know.
        </li>
        <li>
          Be succinct and clear - You only 1,000 characters for your alt text on
          Twitter, so it’s better to be brief and direct.
        </li>
        <li>
          Be objective - Unless it's an image of yourself, or you know exactly
          what's happening in the image, don't editorialize or make assumptions
          about what's happening.
        </li>
        <li>
          Use regular sentence structure - Use complete sentences! Don’t just
          write bullet points of the key characteristics.
        </li>
        <li>
          Use plain language - This is not the place to prove that you know
          Shakespearean English. Resist the urge to be ornate or overly effusive
          with your descriptions and stick to writing in plain language. You can
          be a bit creative, just don’t go overboard.
        </li>
      </ol>
      {platform === "twitter" ? <TwitterHowTo /> : null}
      <Continue
        pages={1}
        index={index}
        setIndex={setIndex}
        setAnswer={setAnswer}
      />{" "}
    </>
  );
};

export default AltTxt;
